# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QRCodeReader' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QRCodeReader
	pod 'Socket.IO-Client-Swift', '~> 14.0.0'
	pod 'Alamofire'
	pod 'Charts'
    pod 'SwiftKeychainWrapper', '~> 3.2'

end
